typealias FileTreeSelectionSnapshot = WorkspaceFileTreePresentationSnapshot
typealias FileTreeFolderSnapshot = WorkspaceFileTreeFolderPresentation
typealias FileTreeFileSnapshot = WorkspaceFileTreeFilePresentation
typealias FileTreeNodeSnapshot = WorkspaceFileTreeNodePresentation
