import RepoPromptDomainRuntime

public typealias AgentImageSource = RepoPromptDomainRuntime.AgentImageSource
public typealias AgentImageAttachment = RepoPromptDomainRuntime.AgentImageAttachment
public typealias AgentTaggedFileAttachment = RepoPromptDomainRuntime.AgentTaggedFileAttachment
